### PR TITLE
Ft add VPN app manager for CFA

### PR DESCRIPTION
**Pull request by esirK**
Adds a backend app that allows

- Generating Outline VPN keys from a JSON of emails
- Sends outline keys via email.

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
👍🏽 

---

1. Lets give it a generic name. It has nothing to do with CfA i.e. it's just cli app to generate Outline VPN keys and email them out... `outline-key-mailor` or `okr` or anything in line with that is a good start.
2. Can you may be describe the application architecture a bit? The JSON file structure, the many abstract classes, etc., seem like an overkill but may be there is a reason why you're going in this direction.

**Comment by esirK** [comment]
> 1. Lets give it a generic name. It has nothing to do with CfA i.e. it's just cli app to generate Outline VPN keys and email them out... `outline-key-mailor` or `okr` or anything in line with that is a good start.
> 2. Can you may be describe the application architecture a bit? The JSON file structure, the many abstract classes, etc., seem like an overkill but may be there is a reason why you're going in this direction.

Sure @kilemensi 
I'll describe the architecture here and if it makes sense add it to the README.

As you have mentioned we should give the app a generic name since it has nothing (specific) to do with CFA. Maybe I should also rename some of the `ENVs`.

The architecture tries to allow anyone to generate Outline VPN keys and send them out using SendGrid.

However, we shouldn't force ourselves/others to just use Outline and SendGrid.
The current architecture allows us/anyone else to use any other `VPN` e.g `OpenVPN` just by inheriting the base `VPN` class and implementing just the `generate_vpn_keys` and `get_vpn_keys` methods.

It also allows us to use any `EmailSender` (maybe it should just be `Sender`) and not just `SendGrid` by inheriting the `EmailSender` base class and implementing the `send` method.

For the `EmailsLoader` base class, this is also basically the same reason; As we had discussed, at some point we will want to use `GoogleSheet` as the source of the `Emails` we want to generate VPN keys for.
Going with a base `EmailsLoader`/`Source` that defines `WHAT` is needed to be able to get emails allows us to have different classes e.g one for Loading emails from a local file system, we could have another for loading emails from a google sheet or even from an API. All the system will then need is a directive on where it should load the `emails` from.

**The JSON file structure**
```
{"emails": [{"name": "testemail@domain.com", "has_vpn_access": false,  "sent": false}, {"name": "testemail2@domain.com", "has_vpn_access": true,  "sent": false}]}
```
- The name is just the email we use for the key name and when sending out the email.
- The `has_vpn_access` just allows us to know if the current `email` already has a VPN key. This will prevent regenerating keys for an email.
- The `sent` key is just for allowing us to know if the generated VPN key has been sent to prevent sending out the key again.

Ideally this will be the same structure on the Google Sheet or any other source.

**Comment by kilemensi** [comment]
Thanks @esirK :

> However, we shouldn't force ourselves/others to just use Outline and SendGrid. The current architecture allows us/anyone else to use any other `VPN` e.g `OpenVPN` just by inheriting the base `VPN` class and implementing just the `generate_vpn_keys` and `get_vpn_keys` methods.
> 
> It also allows us to use any `EmailSender` (maybe it should just be `Sender`) and not just `SendGrid` by inheriting the `EmailSender` base class and implementing the `send` method.
> 
> For the `EmailsLoader` base class, this is also basically the same reason; As we had discussed, at some point we will want to use `GoogleSheet` as the source of the `Emails` we want to generate VPN keys for. Going with a base `EmailsLoader`/`Source` that defines `WHAT` is needed to be able to get emails allows us to have different classes e.g one for Loading emails from a local file system, we could have another for loading emails from a google sheet or even from an API. All the system will then need is a directive on where it should load the `emails` from.
> 

While theoretically this sounds like a plan, it's a bad strategy technically. We're not trying to come up with universal solution, but **a** solution to the current problem _we_ face: Outline key generation and distribution.

 * We use Outline, and hence our solution should just cater to Outline for now,
 * We prefer SendGrid, and again, our solution should work with that for now, and
 * Since we plan to support gSheet, starting with CSV would have been my preferred method since a gSheet can be download as CSV directly.

If down-the-line someone (or our requirements change) and we need to support another provider (VPN and/or email), we can `refactor` the code to support that.

> **The JSON file structure**
> 
> ```
> {"emails": [{"name": "testemail@domain.com", "has_vpn_access": false,  "sent": false}, {"name": "testemail2@domain.com", "has_vpn_access": true,  "sent": false}]}
> ```
> 
>     * The name is just the email we use for the key name and when sending out the email.
> 
>     * The `has_vpn_access` just allows us to know if the current `email` already has a VPN key. This will prevent regenerating keys for an email.
> 
>     * The `sent` key is just for allowing us to know if the generated VPN key has been sent to prevent sending out the key again.
> 
> 
> Ideally this will be the same structure on the Google Sheet or any other source.
>

My understanding is we only need an email:

 * We'll generate key for an email and send it via that email.
 * If you generate a key and sending via email fail, delete the key & report to the user running the app.

Since outline allows associating a key with some string & we're associating keys with emails, we don't need to remember anything else. When the program starts, it can load all keys and before generating a new key, check if a key with a given email already exists. If it does, no need to generate, just resend the key again.

In the future we can even add ability to detect if a single email has more than one key associated with it, etc.

**Comment by esirK** [comment]
> Thanks @esirK :
> 
> While theoretically, this sounds like a plan, it's a bad strategy technically. We're not trying to come up with universal solution, but **a** solution to the current problem _we_ face: Outline key generation and distribution.
> 
> * We use Outline, and hence our solution should just cater to Outline for now,
> * We prefer SendGrid, and again, our solution should work with that for now, and
> * Since we plan to support gSheet, starting with CSV would have been my preferred method since a gSheet can be download as CSV directly.
> 
> If down-the-line someone (or our requirements change) and we need to support another provider (VPN and/or email), we can `refactor` the code to support that.
> 

I see what you mean @kilemensi  but I do disagree with some of the reasons given.

Despite the fact that we are only solving for `Outline` and `SendGrid` (Which we are actually implementing), I think every system should be built with `Extensibility/Flexibility` in mind.

> * We use Outline, and hence our solution should just cater to Outline for now,
>* We prefer SendGrid, and again, our solution should work with that for now, and

I agree and I'm not sure if the current solution is against that. What it does is it allows the system to be more `Open/Closed` such that when anyone else decides to use another `VPN/Email sender`, they won't be required to modify/edit the old code to support the new VPN.

I think having a solution/culture of creating solutions that allow easy extension(Which I think we do for the most part) is better than having just one-time scripts. i.e as long as the solution has other possible usecases and doing so won't terribly slow us down or make the system ununderstandable. 
 
>* Since we plan to support gSheet, starting with CSV would have been my preferred method since a gSheet can be download as CSV directly.

I see. I think this is just a file format discussion since we might even decide to be getting the `emails` directly from the `CFA` slack channel which has all `users` directly via slack `API` which I think would be sending us the data in `JSON` format.

> > 
> My understanding is we only need an email:
> 
> * We'll generate key for an email and send it via that email.
> * If you generate a key and sending via email fail, delete the key & report to the user running the app.
> 

This might be true but I feel like we are tightly coupling `key` **generation** with `key` **sending** I think these two should be totally separate. I should be able to **generate** keys at any time and independently send the keys at another time in the future. Having the 2 extra fields allows this to happen.

**Comment by kilemensi** [comment]
> ... Extensibility/Flexibility ...
>

You're confusing extensibility with a universal solution aka silver bullets @esirK . You always, always have to define a problem (and solution) before even implementing it. If you're building a new app right now, are you going to build it with possibility of using Postgres, MySQL, SQLite, <add your proffered DB here>, or are you going to pick one DB you're intimately familiar with, and solve your problem?

> ...having just one-time scripts....
>

A solution to a single well defined problem is not a one-time script, it's a solution to that problem. If the solution is successful, then you can worry about supporting other alternatives providers, etc.. And if your solution is not successful, you haven't wasted any resources on things no one will ever use. If you're going to fail; fail fast, YAGNI, Feature Creep, Over-engineering, etc., are all hard lessons that people learnt going down this road.

> ... just a file format discussion since we might even decide to ...
>

No, it's not just a file format discussion. It's a problem definition: What are we trying to solve, when. My understanding is we want gSheet integration and hence CVS could be seen as a stop gap. Not sure why Slack is even in discussion here... CfA Slack workspace has employees, partners, friends, etc., i.e. not a good source of list of employees only.

> This might be true but I feel like we are tightly coupling...
>

It could be @esirK but what is the point/value of generating a key and **NOT** emailing it? Isn't the ability to email these keys the PRIMARY reason why we're even building this app?

> Having the 2 extra fields allows this to happen.
>

Biggest issue with this (forgetting even the point above) is you're keeping these fields locally. If I run the command today and you run it tomorrow, my local JSON will not be the same as your local JSON... unless we device a JSON syncing solution. Why not just use information we can get from Outline?

**Comment by esirK** [comment]
Looking at other alternatives to the implementation @kilemensi 

I might be wrong but.

> You're confusing extensibility with a universal solution aka silver bullets @esirK . You always, always have to define a problem (and solution) before even implementing it. If you're building a new app right now, are you going to build it with possibility of using Postgres, MySQL, SQLite, , or are you going to pick one DB you're intimately familiar with, and solve your problem?

I'm not sure the current solution is trying to create a universal solution what it's doing (from your example) is creating a `Base class` e.g `BaseDatabaseWrapper:` in Django that defines `WHAT` methods are to be expected/defined by any Database that inherits the base class which will ensure anyone can call a `save` method without worrying about the underlying database. In our case, the base classes also just define the `WHAT` and not doing the actual implementation.

But to answer your question, I would pick a DB I'm familiar with but also allow myself to later add other databases.

> 
> > ...having just one-time scripts....
> 
> A solution to a single well-defined problem is not a one-time script, it's a solution to that problem. If the solution is successful, then you can worry about supporting other alternative providers, etc. And if your solution is not successful, you haven't wasted any resources on things no one will ever use. If you're going to fail; fail fast, YAGNI, Feature Creep, Over-engineering, etc., are all hard lessons that people learned going down this road.

I 💯  agree with this @kilemensi  my point is we are always starting with 1 provider just that we are allowing the system to be extensible and support other providers.

I think what we are doing is just providing a base interface and for any class that inherits from it, we are sure it implements the base methods we require to perform our actions e.g `create_keys`. We aren't actually trying to solve how the other providers act.

> 
> > ... just a file format discussion since we might even decide to ...
> 
> No, it's not just a file format discussion. It's a problem definition: What are we trying to solve, when. My understanding is we want gSheet integration and hence CVS could be seen as a stop gap. Not sure why Slack is even in discussion here... CfA Slack workspace has employees, partners, friends, etc., i.e. not a good source of list of employees only.
>

Cool cool. Although I would think something like `hr` channel would have only current members. It would be great since we wouldn't need any human intervention for the whole process.

> > This might be true but I feel like we are tightly coupling...
> 
> It could be @esirK but what is the point/value of generating a key and **NOT** emailing it? Isn't the ability to email these keys the PRIMARY reason why we're even building this app?
> 

We do have to email it just that one doesn't have to depend on the other. `Send Grid` might be down 😂. The proposed solution to send existing keys would solve this though.

> > Having the 2 extra fields allows this to happen.
> 
> Biggest issue with this (forgetting even the point above) is you're keeping these fields locally. If I run the command today and you run it tomorrow, my local JSON will not be the same as your local JSON... unless we device a JSON syncing solution. Why not just use information we can get from Outline?

Yeah yeah, I agree.

**Comment by kilemensi** [comment]
> I'm not sure the current solution is trying to create a universal solution what it's doing (from your example) is creating a `Base class` e.g `BaseDatabaseWrapper:` in Django that defines `WHAT` methods are to be expected/defined by any Database that inherits the base class which will ensure anyone can call a `save` method without worrying about the underlying database. In our case, the base classes also just define the `WHAT` and not doing the actual implementation.
> 

And that's exactly what I mean @esirK: Django is already a **successful** solution. This is not... yet at least.

>> I 100 agree with this @kilemensi my point is we are always starting with 1 provider just that we are allowing the system to be extensible and support other providers.
> 

Have you also considered the fact supporting other providers is not as straight forward as in this PR? For example, the email template you have will only work for Outline but not necessarily OponVPN. main still need to understand how to instantiate all providers, meaning when a new provider is added, main will need to updated as well (which may include different environment variables as well), etc., etc. Why not leave all that complication out until you really need it?

**Pull request closed without merging**
