### PR TITLE
Adds a github workflow for twoops tracker

### PR DESCRIPTION
**Pull request by esirK**
## Description

Adds a GitHub workflow for building twoops tracker image, pushing it to dockerhub and deploying it to dokku

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by esirK** [comment]
> 1. I think we've been forgetting to run lint/format/tests before merging to `main`.

I think we can add as a different workflow instead of inside the deployment workflow right?

> 3. Just to confirm, `pants publish` pushes the built image to docker hub directly, yes?

Yes

> 4. I take it we'll still extract common things like application name to `env`

Yes. Will do.

**Comment by kilemensi** [comment]
> I think we can add as a different workflow instead of inside the deployment workflow right?
>

The goal is to fail the build/deploy if there are linting/testing errors. If one workflow failing can stop another from proceeding then all good @esirK.

**Review by kilemensi — APPROVED** [review]
🚀

**Comment by esirK** [comment]
@thepsalmist  I think this was one of the first attempt to add CI

**Comment by esirK** [comment]
no @kilemensi

**Pull request closed without merging**
