### PR TITLE
Add script to generate and send outline vpn keys to new hires

### PR DESCRIPTION
**Pull request by koechkevin**
## Description

This PR adds a script to generate outline VPN keys and send emails to new hires.

To test this PR,
- Create virtual environment and activate it.
- Install requirements `pip install -r py/requirements.txt`
- Update .env with the following variables
```
 CFA_GOOGLE_CREDENTIALS_PATH="cfa_vpn/py/credentials.json" # Google Services Credentials.json obtained from GCP
CFA_NEW_HIRES_SHEET_ID="FMfcgzGwJvfQQgxRxxzxJqLdplTldZdM"#Sheet ID that gets updated periodically as new hires come in
CFA_NEW_HIRES_SHEET_NAME="New Hires" # Name of the sheet to get a list from.
```
This PR assumes that column titles are as  they are in [this document](https://docs.google.com/spreadsheets/d/1IOW8cAQg7znb0oW-OSVosvVjEQCOfFlonM7kCQDYmyA/edit?usp=sharing)
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
QQ @koechkevin, how do we deploy this?

**Comment by koechkevin** [comment]
> QQ @koechkevin, how do we deploy this?

@kilemensi I think since this is going to execute as cron job, we only need to identify the server to add the exec script to crontab file to schedule.

**Comment by kilemensi** [comment]
I thought we've standardised on Docker/Dokku deployments @koechkevin?

**Review by kilemensi — COMMENTED** [review]
👍🏽 

---

1. Can this be triggered manually?
2. Is this for new keys only? Or how do I use it to resend a key to someone who has lost/forgotten their key?

**Comment by kilemensi** [comment]
Implemented in https://github.com/CodeForAfrica/ui/pull/681

**Pull request closed without merging**
